import { Signal } from './types';

export async function ingestMockSignals(): Promise<Signal[]> {
  const now = Date.now();

  return [
    {
      id: 'sig_weather_01',
      title: 'Cool rain break from 12:00–16:00',
      summary: 'Dry midday window supports a focused field walk and retail pulse check.',
      details:
        'Morning showers taper by noon, with lower wind and stable visibility downtown. Useful for in-person sensing between deep work blocks.',
      source: 'weather/noaa-local',
      category: 'weather',
      timestamp: new Date(now - 1000 * 60 * 20).toISOString(),
      lat: 45.5231,
      lng: -122.6765,
      distanceFromFocusKm: 1.8,
      noveltyScore: 0.58,
      hypeScore: 0.05,
      actionabilityScore: 0.82,
      credibilityScore: 0.94,
      emotionalIntensityScore: 0.12,
      strategicAlignmentScore: 0.72,
      operationalImpactScore: 0.8,
      timingScore: 0.94,
      column: 'left',
      horizon: 'daily',
      tags: ['weather', 'fieldwork']
    },
    {
      id: 'sig_calendar_01',
      title: 'Two protected strategy blocks are still open',
      summary: '09:30–11:00 and 15:00–16:30 remain unscheduled for synthesis work.',
      details:
        'Shift low-value administrative tasks to after 17:00. Preserve these blocks for narrative mapping and signal annotation.',
      source: 'calendar/local',
      category: 'calendar',
      timestamp: new Date(now - 1000 * 60 * 30).toISOString(),
      lat: null,
      lng: null,
      distanceFromFocusKm: null,
      noveltyScore: 0.4,
      hypeScore: 0,
      actionabilityScore: 0.91,
      credibilityScore: 1,
      emotionalIntensityScore: 0.08,
      strategicAlignmentScore: 0.9,
      operationalImpactScore: 0.93,
      timingScore: 0.98,
      column: 'left',
      horizon: 'daily',
      tags: ['calendar', 'deep-work']
    },
    {
      id: 'sig_local_01',
      title: 'Foot traffic shifted one corridor east this week',
      summary: 'Neighborhood pulse indicates a stronger afternoon cluster around transit edge.',
      details:
        'Three local business updates and two event boards show increased dwell time east of the usual route. Validate with a short observational loop.',
      source: 'local-events/curated',
      category: 'local_pulse',
      timestamp: new Date(now - 1000 * 60 * 75).toISOString(),
      lat: 45.5219,
      lng: -122.6674,
      distanceFromFocusKm: 2.6,
      noveltyScore: 0.74,
      hypeScore: 0.21,
      actionabilityScore: 0.86,
      credibilityScore: 0.77,
      emotionalIntensityScore: 0.22,
      strategicAlignmentScore: 0.81,
      operationalImpactScore: 0.84,
      timingScore: 0.73,
      column: 'center',
      horizon: 'weekly',
      tags: ['city', 'retail-intuition']
    },
    {
      id: 'sig_creative_01',
      title: 'Studios are shipping local-first creative AI workflows',
      summary: 'Small teams are replacing cloud-only stacks with hybrid private inference.',
      details:
        'This aligns with sovereignty and calmer operator ergonomics. Opportunity: package a lightweight local-first service narrative.',
      source: 'creative-tech/briefing',
      category: 'creative_tech',
      timestamp: new Date(now - 1000 * 60 * 130).toISOString(),
      lat: null,
      lng: null,
      distanceFromFocusKm: null,
      noveltyScore: 0.8,
      hypeScore: 0.34,
      actionabilityScore: 0.78,
      credibilityScore: 0.82,
      emotionalIntensityScore: 0.2,
      strategicAlignmentScore: 0.95,
      operationalImpactScore: 0.71,
      timingScore: 0.67,
      column: 'center',
      horizon: 'monthly',
      tags: ['creative-ai', 'positioning']
    },
    {
      id: 'sig_macro_01',
      title: 'Hiring narratives emphasize AI orchestration over pure tooling',
      summary: 'Leadership demand is tilting toward strategic integrators.',
      details:
        'Signals across job language and founder commentary indicate demand for operators who can synthesize product, data, and narrative direction.',
      source: 'macro/hiring-signals',
      category: 'macro_force',
      timestamp: new Date(now - 1000 * 60 * 180).toISOString(),
      lat: null,
      lng: null,
      distanceFromFocusKm: null,
      noveltyScore: 0.61,
      hypeScore: 0.39,
      actionabilityScore: 0.66,
      credibilityScore: 0.75,
      emotionalIntensityScore: 0.27,
      strategicAlignmentScore: 0.89,
      operationalImpactScore: 0.68,
      timingScore: 0.64,
      column: 'center',
      horizon: 'long_term',
      tags: ['career', 'macro']
    },
    {
      id: 'sig_noise_01',
      title: 'Viral discourse storm in general tech feed',
      summary: 'High emotional velocity with low operational relevance for current strategy.',
      details:
        'Story is broadly repeated and weakly tied to local execution choices. Keep monitored but suppressed in default brief.',
      source: 'social/noise-monitor',
      category: 'noise',
      timestamp: new Date(now - 1000 * 60 * 40).toISOString(),
      lat: null,
      lng: null,
      distanceFromFocusKm: null,
      noveltyScore: 0.25,
      hypeScore: 0.94,
      actionabilityScore: 0.14,
      credibilityScore: 0.42,
      emotionalIntensityScore: 0.92,
      strategicAlignmentScore: 0.11,
      operationalImpactScore: 0.16,
      timingScore: 0.35,
      column: 'right',
      horizon: 'daily',
      tags: ['noise', 'suppressed']
    }
  ];
}
